name = "scrutinizer-relay"
main = "worker.js"
compatibility_date = "2024-09-23"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "scrutinizer-reports"

[[kv_namespaces]]
binding = "RATELIMIT"
id = "8b73a76a19b6431985dfae054b31d057"
